# Generated by Django 3.0.4 on 2020-03-18 00:12

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200317_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zauthuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, null=True, region=None, unique=True),
        ),
    ]
