# Generated by Django 3.0.4 on 2020-03-24 18:14

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200318_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationinfo',
            name='edu_code',
            field=models.CharField(blank=True, default='', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='National code must be a decimal sequence', regex='\\d{8,15}')]),
        ),
        migrations.AlterField(
            model_name='zuser',
            name='nat_code',
            field=models.CharField(blank=True, default='', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='National code must be a decimal sequence', regex='\\d*')]),
        ),
        migrations.AlterField(
            model_name='zuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None, unique=True),
        ),
    ]
