# Generated by Django 3.0.4 on 2020-03-24 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200324_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.City'),
        ),
    ]
