# Generated by Django 3.0.4 on 2020-03-24 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200324_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zuser',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='zuser',
            name='education',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='accounts.EducationInfo'),
        ),
    ]
