# Generated by Django 3.0.4 on 2020-03-27 01:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200324_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationinfo',
            name='edu_code',
            field=models.CharField(default=None, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='National code must be a decimal sequence', regex='\\d{8,15}')]),
        ),
        migrations.AlterField(
            model_name='educationinfo',
            name='field',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Field'),
        ),
        migrations.AlterField(
            model_name='educationinfo',
            name='grade',
            field=models.CharField(choices=[('before', 'Before university'), ('bachelor', 'Bachelor of science'), ('master', 'Master of science'), ('phd', 'Ph.D'), ('after', 'After Ph.D')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='educationinfo',
            name='university',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.University'),
        ),
        migrations.AlterField(
            model_name='zuser',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='zuser',
            name='city',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.City'),
        ),
        migrations.AlterField(
            model_name='zuser',
            name='education',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='accounts.EducationInfo'),
        ),
        migrations.AlterField(
            model_name='zuser',
            name='nat_code',
            field=models.CharField(default=None, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='National code must be a decimal sequence', regex='\\d*')]),
        ),
        migrations.AlterField(
            model_name='zuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, null=True, region=None, unique=True),
        ),
    ]
