# Generated by Django 3.0.4 on 2020-03-27 22:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200327_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zuser',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='zuser',
            name='city',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.City'),
        ),
        migrations.AlterField(
            model_name='zuser',
            name='education',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='accounts.EducationInfo'),
        ),
        migrations.AlterField(
            model_name='zuser',
            name='nat_code',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='National code must be a decimal sequence', regex='\\d*')]),
        ),
        migrations.AlterField(
            model_name='zuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region=None, unique=True),
        ),
    ]
