# Generated by Django 3.0.4 on 2020-03-28 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import events.utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200327_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=events.utils.generate_random_string, max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
