# Generated by Django 3.0.4 on 2020-03-23 06:04

from django.db import migrations, models
import events.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('public_key', models.CharField(default=events.utils.generate_random_string, max_length=128, unique=True)),
                ('private_key', models.CharField(default=events.utils.generate_random_string, max_length=128, unique=True)),
            ],
        ),
    ]
